---
- name: Switch configuration inbound 2
  hosts: cisco_switch_in_two

  tasks:
  - name: Creating VLANs
    cisco.ios.ios_vlans:
      config:
        - name: VLAN10
          vlan_id: 10
          state: active
          shutdown: disabled
        - name: VLAN20
          vlan_id: 20
          state: active
          shutdown: disabled
      state: merged

  - name: Configure Interfaces
    cisco.ios.ios_l2_interfaces:
      config:
        - name: FastEthernet0/1
          mode: access
          access:
            vlan: 10
        - name: FastEthernet0/2
          mode: access
          access:
            vlan: 20
      state: merged

  - name: Configure Etherchannel
    cisco.ios.ios_config:
      lines:
        - channel-protocol pagp
        - channel-group 1 mode desirable
      parents: "{{ item }}"
    with_items:
      - interface FastEthernet0/23
      - interface FastEthernet0/24